name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build CLI
        run: make

      - name: Build & Run Tests
        run: |
          make test

      - name: Run Example
        run: |
          ./csvparse examples/sample.csv | head -n 3

      - name: Benchmark
        run: make bench